/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCreateRouteImport } from './routes/_authed/invite/$inviteId.tsx'
import { Route as AuthedTripsIndexRouteImport } from './routes/_authed/trips/index'
import { Route as AuthedTripsTripIdRouteImport } from './routes/_authed/trips/$tripId'
import { Route as AuthedInviteInviteIdRouteImport } from './routes/_authed/invite/$inviteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsIndexRoute = AuthedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsTripIdRoute = AuthedTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInviteInviteIdRoute = AuthedInviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof AuthedInviteInviteIdRoute
  '/trips/$tripId': typeof AuthedTripsTripIdRoute
  '/trips': typeof AuthedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/create': typeof AuthedCreateRoute
  '/invite/$inviteId': typeof AuthedInviteInviteIdRoute
  '/trips/$tripId': typeof AuthedTripsTripIdRoute
  '/trips': typeof AuthedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/_authed/invite/$inviteId': typeof AuthedInviteInviteIdRoute
  '/_authed/trips/$tripId': typeof AuthedTripsTripIdRoute
  '/_authed/trips/': typeof AuthedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/create'
    | '/invite/$inviteId'
    | '/trips/$tripId'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/create'
    | '/invite/$inviteId'
    | '/trips/$tripId'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/create'
    | '/_authed/invite/$inviteId'
    | '/_authed/trips/$tripId'
    | '/_authed/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/': {
      id: '/_authed/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthedTripsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/$tripId': {
      id: '/_authed/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthedTripsTripIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invite/$inviteId': {
      id: '/_authed/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof AuthedInviteInviteIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedInviteInviteIdRoute: typeof AuthedInviteInviteIdRoute
  AuthedTripsTripIdRoute: typeof AuthedTripsTripIdRoute
  AuthedTripsIndexRoute: typeof AuthedTripsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedInviteInviteIdRoute: AuthedInviteInviteIdRoute,
  AuthedTripsTripIdRoute: AuthedTripsTripIdRoute,
  AuthedTripsIndexRoute: AuthedTripsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
